---
title: "[Re] Figure 4 Altschul and Gish (1996)"
author: "Nathan Brouwer"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The following code is contains intial information for replicating Figure 4 of Altchul and Gish 1996.  IT IS NOT YET COMPLETE.


## Preliminaries

```{r}
library(Biostrings)
```

## Sequences

```{r}
# UniProtKB - P40582 (GST1_YEAST)
# https://www.uniprot.org/uniprot/P40582
# Glutathione S-transferase 1
P40582 <- c("MSLPIIKVHWLDHSRAFRLLWLLDHLNLEYEIVPYKRDANFRAPPELKKIHPLGRSPLLE
VQDRETGKKKILAESGFIFQYVLQHFDHSHVLMSEDADIADQINYYLFYVEGSLQPPLMI
EFILSKVKDSGMPFPISYLARKVADKISQAYSSGEVKNQFDFVEGEISKNNGYLVDGKLS
GADILMSFPLQMAFERKFAAPEDYPAISKWLKTITSEESYAASKEKARALGSNF")
P40582 <- gsub("\n","",P40582)


# UniProtKB - P41042 (RS4_DROME)
# https://www.uniprot.org/uniprot/P41042
P41042 <- c("MADEAQAPPAEGAPPAEGEAPPPAEGAEGAVEGGEAAPPAEPAEPIKHSYTLFYFNVKAL
AEPLRYLFAYGNQEYEDVRVTRDEWPALKPTMPMGQMPVLEVDGKRVHQSISMARFLAKT
VGLCGATPWEDLQIDIVVDTINDFRLKIAVVSYEPEDEIKEKKLVTLNAEVIPFYLEKLE
QTVKDNDGHLALGKLTWADVYFAGITDYMNYMVKRDLLEPYPALRGVVDAVNALEPIKAW
IEKRPVTEV")

P41042 <- gsub("\n","",P41042)


# https://www.uniprot.org/uniprot/P41043
# UniProtKB - P41043 (GSTS1_DROME)
# Drosophila melanogaster (Fruit fly)
# GstS1

P41043 <- c("MADEAQAPPAEGAPPAEGEAPPPAEGAEGAVEGGEAAPPAEPAEPIKHSYTLFYFNVKALAEPLRYLFAYGNQEYEDVRVTRDEWPALKPTMPMGQMPVLEVDGKRVHQSISMARFLAKT
VGLCGATPWEDLQIDIVVDTINDFRLKIAVVSYEPEDEIKEKKLVTLNAEVIPFYLEKLE
QTVKDNDGHLALGKLTWADVYFAGITDYMNYMVKRDLLEPYPALRGVVDAVNALEPIKAW
IEKRPVTEV")
```


```{r}
P40582 <- gsub("\n","",P40582)
P41042 <- gsub("\n","",P41042)
P41043 <- gsub("\n","",P41043)


```






```{r}
align <- Biostrings::pairwiseAlignment(P40582,
                  P41043,
                  type = "local",
                  gapOpening=12, 
                  gapExtension=2,
                  substitutionMatrix="BLOSUM62")
```


Biostrings - 56
blastp - gapped: 62
