---
title: "Altschul and Gish - Score random alignment"
author: "Nathan Brouwer"
date: "10/29/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Function to simulate and score 2 polypeptides


### Version 1

```{r}
r_alignments_score_vs1 <- function(seq.length1,
                                      seq.length2,
                                      aas,
                                      aas.freqs,
                                      alignment.type = "local",
                    gap.open = 12, 
                    gap.extend = 1){

  # Create random sequences
  ## create 1st sequence with sample()
  seq.n.i <- sample(x = aas, 
                  size = seq.length1, 
                  replace = TRUE, 
                  prob = aas.freqs)
  
  ## create 2nd sequence
  seq.m.i <- sample(x = aas, 
                  size = seq.length2, 
                  replace = TRUE, 
                  prob = aas.freqs)
 
  ## turn sequences in to character strings with paste()
  seq.n.i <- paste(seq.n.i,sep = "",collapse = "")
  seq.m.i <- paste(seq.m.i,sep = "",collapse = "")
  
  # Align the sequences
  alignment.i <- pairwiseAlignment(pattern = AAString(seq.n.i), 
                                   subject = AAString(seq.m.i),
                    type               = alignment.type,
                    substitutionMatrix = "BLOSUM62",
                    gapOpening         = gap.open,
                    gapExtension       = gap.extend)
  
  # Extract information from the alignment
  score.i         <- score(alignment.i)
  alignment.seq.i <- toString(alignment.i)
  length.i        <- nchar(alignment.seq.i)

  
        output  <- c(score.i,  length.i,  seq.length1,  seq.length2)
  names(output) <- c("score.i","length.i","seq.length1",
                     "seq.length2")
  
  return(output)
}  
                    


```



Test
```{r}
r_alignments_score_vs1(seq.length1 = 191,
                       seq.length2 = 191,
                       aas = robinson.aafreq$aa1,
                       aas.freqs = robinson.aafreq$aa.freq,
                                      alignment.type = "local")
```


### Version 2


```{r}
r_alignments_score_vs2 <- function(seq.length1 = 1000,
                                 seq.length2 = 1000,
                                 aas = LETTERS[-c(5,8,15,21,24,26)],
                                 aas.freqs = rep(1,20),
                                 alignment.type = "local",
                                 gap.open = 12, 
                                 gap.extend = 1){
  
  if(length(aas) == 1){
    if(aas == "ROBINSON")
    {
    aas.freqs <- c(35155,8669,24161,28354,17367,
             33229,9906,23161,25872,40625,
             10101,20212,23435,19208,23105,
             32070,26311,29012,5990,14488)
    aas.freqs<-aas.freqs/sum(aas.freqs)
    
    aas <- c("A","C","D","E","F",
             "G","H","I","K","L",
             "M","N","P","G","R",
             "S","T","V","W" ,"Y")
    # TO DO: insert message: setting defaults to...
    
    }
  }

  # Create random sequences
  ## create 1st sequence with sample()
  seq.n.i <- r_molec_seq(units = aas,
                prob = aas.freqs,
                length = seq.length1)
  
  ## create 2nd sequence
  seq.m.i <- r_molec_seq(units = aas,
                prob = aas.freqs,
                length = seq.length1)
  

  
  # Align the sequences
  alignment.i <- pairwiseAlignment(pattern = seq.n.i, 
                                   subject = seq.m.i,
                    type               = alignment.type,
                    substitutionMatrix = "BLOSUM62",
                    gapOpening         = gap.open,
                    gapExtension       = gap.extend)
  
  # Extract information from the alignment
  score.i         <- score(alignment.i)
  alignment.seq.i <- toString(alignment.i)
  length.i        <- nchar(alignment.seq.i)

  
  output  <- c(score.i,  length.i,  seq.length1,  seq.length2)
  names(output) <- c("score.i","length.i","seq.length1",
                     "seq.length2")
  
  return(output)
}  
                    

```


```{r}
r_alignments_score_vs2()
```

