---
title: "Altschul and Gish - Run experiment"
author: "Nathan Brouwer"
date: "10/29/2019"
output: html_document
  highlight: pygment
pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(
  class.source = "numberLines lineAnchors", 
  class.output = c("numberLines lineAnchors chunkout") 
)
```



Tabel 1 Sequence lengths

```{r}
seq.lengths <- c(191,245,314,403,518,665,854,1097,1408,1808,2322,2981)
```


```{r}
run_blaststats_expt <- function(iterations, 
                     seq.length1 = 191,
                     seq.length2 = 191,
                     aas = robinson.aafreq$aa1,
                     aas.freqs = robinson.aafreq$aa.freq.sum.aa.freq.){
  #create dataframe
  random.scores <- data.frame(interation = 1:iterations,
                         score.i = NA,
                         length.i = NA,
                         seq.length1 = NA, 
                         seq.length2 = NA)
  
  #loop
  for(i in 1:iterations){
  out.i <- r_alignments_score(seq.length1 = 2981, 
                      seq.length2 = 2981, 
                      aas = robinson.aafreq$aa1,
                      aas.freqs = robinson.aafreq$aa.freq.sum.aa.freq.)
  
  random.scores[i,-1] <- out.i
  }
  
  return(random.scores)
                     
}
  



```


```{r}
expt191 <- run_blaststats_expt(iterations = 10000,
                    seq.length1 = 191,
                    seq.length1 = 191)
```
